Check file:///[WILDCARD]/trace_ops_caught_error/main.ts
running 1 test from ./test/trace_ops_caught_error/main.ts
handle thrown error in async function ... ok ([WILDCARD])

ok | 1 passed | 0 failed ([WILDCARD])

